[package]
name = "ray"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = "1.13.1"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "net", "macros", "io-util"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
strip = true
debug = false
