[package]
name = "ray"
version = "0.2.0"
edition = "2024"

[dependencies]
uuid = "1.16.0"
tokio = { version = "1.44.1", features = ["rt-multi-thread", "net", "macros", "io-util", "time", "sync"] }
tokio-rustls = { git = "https://github.com/radioactiveAHM/tokio-rustls.git", default-features = false, features = ["ring"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
strip = true
debug = false
