[package]
name = "ray"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = "1.15.1"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "net", "macros", "io-util", "time", "sync"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
strip = true
debug = false
